version: '3'
services:
  mysqldb:
    image: mysql
    ports: 
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: Cybage@123
      MYSQL_DATABASE: club

  springboot-container:
    image: abhi_docker/sportsclub:latest
    build: .
    ports:
      - 8088:8080
    restart: always
    depends_on: 		
      - mysqldb
   
  angular-container:
   image: abhijeet-angular-app
   ports: 
      - 8090:80
