version: '3'
services:
  mysqldb:
    image: mysql
    ports: 
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: Cybage@123
      MYSQL_DATABASE: club
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - abhijeet-ang-springboot-mysql-net

  springboot-container:
    image: abhi_docker/sportsclub:latest
    build: .
    ports:
      - 8088:8080
    restart: always
    depends_on:
      - mysqldb
    networks:
      - abhijeet-ang-springboot-mysql-net

  angular-container:
    image: abhijeet-angular-app
    ports: 
      - 8090:80
    networks:
      - abhijeet-ang-springboot-mysql-net
  
networks:
  abhijeet-ang-springboot-mysql-net:
   driver: bridge

volumes:
  mydb:
